baseURL = "https://benoneill.xyz"
languageCode = "en-us"
title = "Ben O'Neill"
theme = "ananke"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[params]
SidebarRecentLimit = 5

[author]
    name = "Ben O'Neill"

[menu]

	[[menu.main]]
		name = "About"
		url = "https://benoneill.xyz/about/"
		weight = 10
	
	[[menu.main]]
		name = "Links"
		url = "https://benoneill.xyz/links/"
		weight = 20

	[[menu.main]]
		name = "Posts"
		url = "https://benoneill.xyz/posts/"
		weight = 20

	[[menu.main]]
		name = "Projects"
		url = "https://benoneill.xyz/projects/"
		weight = 20
